### ISSUE TITLE
 big images does not get uploaded and there is no feedback

### ISSUE THREAD

**Issue by datenarbeit** [himate/himate#69]

**Comment by chrdavid** [comment]
Ok, this is a server configuration issue, check the screenshot....
![nginx_entity_too_large](https://cloud.githubusercontent.com/assets/15276813/12646592/5087f590-c5d1-11e5-8694-39996f3e9a92.png)

nginx should set the "client_max_body_size"

@fishi0x01 please check.

**Comment by chrdavid** [comment]
nginx configuration updated, please test again

**Comment by simondeichsel** [comment]
seems to work fine for now.
