### ISSUE TITLE
Merchant: Align design/logo with refugee-app

### ISSUE THREAD

**Issue by simondeichsel** [himate/himate#78]

**Comment by sananoussa** [comment]
hi @simondeichsel , can you please explain what this ticket is about ? (only changing the logo on startpage or is there something else ?)

**Comment by simondeichsel** [comment]
@sananoussa it is the logo and and the colors. 
IF you changed fonts, spacings and other details you should copy this, too. But do not spend more than 1-2h. The logo is the only really important thing.

**Comment by sananoussa** [comment]
ok, then this should have been finished on friday, I will merge to develop this week so you can see the changes

**Comment by datenarbeit** [comment]
logi is updated, i will put this ticket into backlog, unless its getting important
