### ISSUE TITLE
restrict max. characters for description, short description and conditions

### ISSUE THREAD

**Issue by simondeichsel** [himate/himate#87]
Restrict the entry fields in the merchant and admin-view to these character limits.
A frontend solution is ok, backend-restriction is better, of course.

short description: 100 utf8 characters (for any language)
(long) description: 400 characters
Konditionen: 400 characters

**Comment by simondeichsel** [comment]
@sananoussa can you do it from the frontend? How much work is it?

**Comment by sananoussa** [comment]
done .. I deployed to test version

**Comment by simondeichsel** [comment]
@sananoussa nice! works for me, please deploy to live as soon as you have time!
